### ISSUE TITLE
Question about RuntimeError: tensors on different device, may cause by offloading

### ISSUE THREAD

**Issue by jinghan23** [EvolvingLMMs-Lab/LongVA#23]
Hi, thanks for your amazing work. I'm reproducing the process of length extension to 224k on one node with `extend_qwen2.sh` and I got the following running error:

```
Traceback (most recent call last):
  File "/home/jzhangjv/files/LongVA/text_extend/text_extend_train.py", line 265, in <module>
    main(args.parse_args())
  File "/home/jzhangjv/files/LongVA/text_extend/text_extend_train.py", line 177, in main
    accelerator.backward(loss)
  File "/home/jzhangjv/.conda/envs/longva/lib/python3.10/site-packages/accelerate/accelerator.py", line 2151, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/home/jzhangjv/.conda/envs/longva/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 175, in backward
    self.engine.step()
  File "/home/jzhangjv/.conda/envs/longva/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2169, in step
    self._take_model_step(lr_kwargs)
  File "/home/jzhangjv/.conda/envs/longva/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2075, in _take_model_step
    self.optimizer.step()
  File "/home/jzhangjv/.conda/envs/longva/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/jzhangjv/.conda/envs/longva/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2047, in step
    self.unscale_and_clip_grads(sub_group_id, scaled_global_grad_norm)
  File "/home/jzhangjv/.conda/envs/longva/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/jzhangjv/.conda/envs/longva/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2117, in unscale_and_clip_grads
    self.fp32_partitioned_groups_flat[sub_group_id].grad.mul_(1. / combined_scale)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
I'm running the experiment on one node with 8x80G A800.
I install the conda environment following the instructions on README and it's like:
```
Package                   Version      Editable project location
------------------------- ------------ ----------------------------------
accelerate                0.33.0
aiofiles                  23.2.1
aiohappyeyeballs          2.4.0
aiohttp                   3.10.5
aiosignal                 1.3.1
altair                    5.4.1
annotated-types           0.7.0
anyio                     4.4.0
appdirs                   1.4.4
async-timeout             4.0.3
attrs                     24.2.0
av                        12.3.0
bitsandbytes              0.41.0
certifi                   2022.12.7
charset-normalizer        2.1.1
click                     8.1.7
contourpy                 1.3.0
cycler                    0.12.1
datasets                  2.16.1
decord                    0.6.0
deepspeed                 0.14.2
dill                      0.3.7
docker-pycreds            0.4.0
docstring_parser          0.16
einops                    0.6.1
einops-exts               0.0.4
evaluate                  0.4.2
exceptiongroup            1.2.2
fastapi                   0.112.2
ffmpy                     0.4.0
filelock                  3.13.1
flash-attn                2.6.3
fonttools                 4.53.1
frozenlist                1.4.1
fsspec                    2023.10.0
ftfy                      6.2.3
gitdb                     4.0.11
GitPython                 3.1.43
gradio                    4.29.0
gradio_client             0.16.1
h11                       0.14.0
hf_transfer               0.1.8
hjson                     3.1.0
httpcore                  1.0.5
httpx                     0.27.2
huggingface-hub           0.24.6
idna                      3.4
importlib_resources       6.4.4
iniconfig                 2.0.0
Jinja2                    3.1.3
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
latex2mathml              3.77.0
loguru                    0.7.2
longva                    1.7.0.dev0   /mypath/LongVA/longva
markdown-it-py            3.0.0
markdown2                 2.5.0
MarkupSafe                2.1.5
matplotlib                3.9.2
mdurl                     0.1.2
mpmath                    1.3.0
multidict                 6.0.5
multiprocess              0.70.15
narwhals                  1.6.0
networkx                  3.2.1
ninja                     1.11.1.1
numpy                     1.26.4
open_clip_torch           2.26.1
opencv-python             4.10.0.84
orjson                    3.10.7
packaging                 24.1
pandas                    2.2.2
peft                      0.4.0
pillow                    10.2.0
pip                       24.2
pluggy                    1.5.0
protobuf                  4.25.4
psutil                    6.0.0
py-cpuinfo                9.0.0
pyarrow                   17.0.0
pyarrow-hotfix            0.6
pydantic                  2.8.2
pydantic_core             2.20.1
pydub                     0.25.1
Pygments                  2.18.0
pynvml                    11.5.3
pyparsing                 3.1.4
pytest                    8.3.2
python-dateutil           2.9.0.post0
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.2
referencing               0.35.1
regex                     2024.7.24
requests                  2.32.3
rich                      13.8.0
ring_flash_attn           0.1
rpds-py                   0.20.0
ruff                      0.6.3
safetensors               0.4.4
scikit-learn              1.2.2
scipy                     1.14.1
seaborn                   0.13.2
semantic-version          2.10.0
sentencepiece             0.1.99
sentry-sdk                2.13.0
setproctitle              1.3.3
setuptools                72.1.0
shellingham               1.5.4
shortuuid                 1.0.13
shtab                     1.7.1
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
starlette                 0.38.2
svgwrite                  1.4.3
sympy                     1.12
threadpoolctl             3.5.0
timm                      1.0.9
tokenizers                0.15.2
tomli                     2.0.1
tomlkit                   0.12.0
torch                     2.1.2+cu118
torchvision               0.16.2+cu118
tqdm                      4.66.5
transformers              4.40.0.dev0
triton                    2.1.0
typer                     0.12.5
typing_extensions         4.12.2
tyro                      0.8.10
tzdata                    2024.1
urllib3                   2.2.2
uvicorn                   0.30.6
wandb                     0.16.5
wavedrom                  2.0.3.post3
wcwidth                   0.2.13
websockets                11.0.3
wheel                     0.43.0
xxhash                    3.5.0
yarl                      1.9.6
```

My cuda version is 11.8 as required. (Before this running, I have got `deepspeed.ops.op_builder.builder.CUDAMismatchException: >- DeepSpeed Op Builder: Installed CUDA version 12.1 does not match the version torch was compiled with 11.8, unable to compile cuda/cpp extensions without a matching cuda version.` so I changed the cuda version to 11.8.)

I'm not so familiar with zero3 offloading so I'm not sure the effect on memory occupation if I just add `.to(device)` to these tensors. Thanks for any help in advance.

**Comment by jinghan23** [comment]
Solved the problem by manually edit the code following https://github.com/microsoft/DeepSpeed/pull/5461/commits/65d6266a1f680b4bfbd8b0a19028019d9a061575.
