### ISSUE TITLE
Thank you for your work. How can we reproduce the V-NIAH benchmark results? 

### ISSUE THREAD

**Issue by fistyee** [EvolvingLMMs-Lab/LongVA#7]

**Comment by jzhang38** [comment]
We cannot provide the haystack video ourselves as we use an actual movie in our evaluation. Specifically, I use the movie "孤注一掷(no more bet)" as the haystack. 

The rest instructions are written the README:

https://github.com/EvolvingLMMs-Lab/LongVA?tab=readme-ov-file#v-niah-evaluation

Let me know if you encounter any problems.

**Comment by fistyee** [comment]
Thanks, could you describe what the duration distribution of clips extracted from movies is, and can you provide more query prompts for LongVA as a reference?

**Comment by jzhang38** [comment]
>  could you describe what the duration distribution of clips extracted from movies i

We do not use clips from the movie. We load the entire movie as the haystack video and sample frames at 1 fps, as stated in the paper and also reflected in our code:

https://github.com/EvolvingLMMs-Lab/LongVA/blob/efc27fdcc9cdc411dee8af296aa1a34ebb29d445/vision_niah/produce_haystack_embedding.py#L12-L21
> can you provide more query prompts for LongVA as a reference?

I am not sure what you mean by "query prompts". If you are looking for needle images & questions, they are here: https://huggingface.co/datasets/lmms-lab/v_niah_needles. 
If you are looking for the prompt template: 
https://github.com/EvolvingLMMs-Lab/LongVA/blob/efc27fdcc9cdc411dee8af296aa1a34ebb29d445/vision_niah/eval_vision_niah.py#L48-L51

**Comment by hello-bluedog** [comment]
![截屏2024-09-10 16 39 54](https://github.com/user-attachments/assets/501e77ae-7558-45cd-a249-448ae8b31219)

**Comment by hello-bluedog** [comment]
I got None logits.Is there any possible reason.
I changed nothing.

**Comment by hello-bluedog** [comment]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/yunzhu/LongVA/vision_niah/eval_vision_niah.py", line 355, in <module>
[rank0]:     main(args.parse_args())
[rank0]:   File "/home/yunzhu/LongVA/vision_niah/eval_vision_niah.py", line 333, in main
[rank0]:     all_accuracies, accelerator = inference(args)
[rank0]:   File "/home/yunzhu/LongVA/vision_niah/eval_vision_niah.py", line 239, in inference
[rank0]:     correct = eval_forward(
[rank0]:   File "/home/yunzhu/LongVA/vision_niah/eval_vision_niah.py", line 106, in eval_forward
[rank0]:     pred = logits.argmax(dim=-1)
[rank0]: AttributeError: 'NoneType' object has no attribute 'argmax'
This is my log.

**Comment by hello-bluedog** [comment]
I Find You set logits=None in forward function of class Qwen2ForCausalLM_RingAttn, which is located at easy_context/modeling_qwen2.py.
I think this a bug, can you fix it?

**Comment by hello-bluedog** [comment]
![Uploading 截屏2024-09-10 17.14.08.png…]()

**Comment by xuanxianyou** [comment]
> I got None logits.Is there any possible reason.我没有得到任何日志。有什么可能的原因吗？ I changed nothing. 我什么也没改变。

Hello, I got the same problem, have you solved it?

**Comment by xuanxianyou** [comment]
> I got None logits.Is there any possible reason. I changed nothing.

Hello, I got the same problem, have you solved it?

**Comment by hello-bluedog** [comment]
I solved it by calculating logits in modeling_qwen_ringattn's forward function
 logits = self.lm_head(hidden_states).float()

in easy_context/modeling_qwen2.py
<img width="785" alt="截屏2024-10-17 06 29 17" src="https://github.com/user-attachments/assets/849d3e37-4077-4f0d-b6d1-77288e7c3d5f">

**Comment by jzhang38** [comment]
@hello-bluedog Hi yes this is a bug introduced by a PR. I just fix this.

**Comment by liyucheng09** [comment]
@jzhang38 Hi Peiyuan, do you consider to add v-NIAH to lmms-eval?
